---
services:
    - docker

env:
    - filebeat_version=7.12.0
    - filebeat_version=7.11.2
    - filebeat_version=7.11.1
    - filebeat_version=7.11.0
    - filebeat_version=7.10.1
    - filebeat_version=7.10.0
    - filebeat_version=7.9.3
    - filebeat_version=7.9.2
    - filebeat_version=7.9.1
    - filebeat_version=7.9.0
    - filebeat_version=7.8.1
    - filebeat_version=7.8.0
    - filebeat_version=7.7.1
    - filebeat_version=7.7.0
    - filebeat_version=7.6.2
    - filebeat_version=7.6.1
    - filebeat_version=7.5.2
    - filebeat_version=7.4.2
    - filebeat_version=7.3.2
    - filebeat_version=7.2.1
    - filebeat_version=7.1.1
    - filebeat_version=7.0.1

script:
    - docker build -f Dockerfile -t honeynet/filebeat:$filebeat_version --build-arg filebeat_version=$filebeat_version .

after_success:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - export REPO=honeynet/filebeat
    - docker push $REPO:$filebeat_version
