---
name: Docker build and push
'on':
  push:
    branches:
      - 'master' 

jobs:

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - filebeat_version: 7.16.1
          - filebeat_version: 7.16.0
          - filebeat_version: 7.15.2
          - filebeat_version: 7.15.1
          - filebeat_version: 7.15.0
          - filebeat_version: 7.14.2
          - filebeat_version: 7.14.1
          - filebeat_version: 7.14.0
          - filebeat_version: 7.13.4
          - filebeat_version: 7.13.3
          - filebeat_version: 7.13.2
          - filebeat_version: 7.13.1
          - filebeat_version: 7.13.0
          - filebeat_version: 7.12.1
          - filebeat_version: 7.12.0
          - filebeat_version: 7.11.2
          - filebeat_version: 7.11.1
          - filebeat_version: 7.11.0
          - filebeat_version: 7.10.1
          - filebeat_version: 7.10.0
          - filebeat_version: 7.9.3
          - filebeat_version: 7.9.2
          - filebeat_version: 7.9.1
          - filebeat_version: 7.9.0
          - filebeat_version: 7.8.1
          - filebeat_version: 7.8.0
          - filebeat_version: 7.7.1
          - filebeat_version: 7.7.0
          - filebeat_version: 7.6.2
          - filebeat_version: 7.6.1
          - filebeat_version: 7.5.2
          - filebeat_version: 7.4.2
          - filebeat_version: 7.3.2
          - filebeat_version: 7.2.1
          - filebeat_version: 7.1.1
          - filebeat_version: 7.0.1

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: quay.io/honeynet/filebeat:${{ matrix.filebeat_version }}
          build-args: |
            filebeat_version=${{ matrix.filebeat_version }}
